import React, { ReactNode } from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ESTUDIANTES",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

const AdminLayout = ({ children }: Props) => {
  return (
    <>
      {/* Aquí puedes agregar la barra de navegación de admin, sidebar, etc. */}
      <main>{children}</main>
      {/* Aquí puedes agregar el footer de admin si es necesario */}
    </>
  );
};

export default AdminLayout;
